name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/icons/home.png
    - assets/icons/working.png
    - assets/icons/lapor.png
    - assets/icons/search.png
    - assets/icons/search2.png
    - assets/icons/notifikasi.png
    - assets/icons/account.png
    - assets/icons/detail_ticket.png
    - assets/images/detail_ticket.png
    - assets/icons/user_list.png
    - assets/icons/team_list.png
    - assets/icons/performance.png

    - assets/icons/allticket.png
    - assets/icons/solve.png
    - assets/icons/todo.png
    - assets/icons/overdue.png

